### ISSUE TITLE
The type or namespace name 'MoroutinesSettings'  could not be found

### ISSUE THREAD

**Issue by tacokhun** [KurbanismailovZaur/Moroutines#2]
After downloading latest zip:

The type or namespace name 'MoroutinesSettings' could not be found (are you missing a using directive or an assembly reference?)

i liked it more when it was compact package, without all the editor stuff, not sure what is the purpose of it.

**Comment by KurbanismailovZaur** [comment]
What version of package you use? You should download Moroutines.unitypackage from Release section and install it. I try it right now and there is no errors.

**Comment by tacokhun** [comment]
I was using master branch, releases dont have this error.
