### ISSUE TITLE
Were there any like bug fixes since the last version i have from before april

### ISSUE THREAD

**Issue by tacokhun** [KurbanismailovZaur/Moroutines#3]
As the repository was completely deleted, and i dont know if i should update it to the current version.

**Comment by KurbanismailovZaur** [comment]
Repository is not deleted. I repair it. You should download latest version. There is no errors as i can see.

**Comment by KurbanismailovZaur** [comment]
Here you can dowload it: 
https://github.com/KurbanismailovZaur/Moroutines/releases
